name: Build project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - staging
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: |
          yarn
          yarn build

  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test project
        run: |
          yarn test:build
