name: Test compiled project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - staging
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test project
        run: |
          yarn jest:build
